import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { FirebirdBrowser, DirectTransport } from 'firebird-wasm/browser';
import { Pak } from '../src/pak.js';
import { createSchema, loadResources, loadMap, SQL_FILES } from '../src/loader.js';
import { Renderer } from '../src/renderer.js';
import { loadPalette } from '../src/pak.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sql = Object.fromEntries(SQL_FILES.map((n) => [n, fs.readFileSync(path.join(root, `sql/${n}.sql`), 'utf8')]));
const db = new FirebirdBrowser('memory://quake', { transport: new DirectTransport() });
await createSchema(db, sql);
const pak = new Pak(fs.readFileSync(path.join(root, 'public/pak/pak0.pak')).buffer);
const res = await loadResources(db, pak); await loadMap(db, pak, res, 'e1m1');
const stub = { getContext: () => ({ createImageData: (w, h) => ({ data: new Uint8ClampedArray(w * h * 4) }), putImageData() {} }) };
const r = new Renderer(stub, { palette: loadPalette(pak.get('gfx/palette.lmp')), colormap: pak.get('gfx/colormap.lmp') });
r.setSize(320, 200);
const last = (await db.query('SELECT * FROM quake_tic(1,0,0,0,0,0,0,1,0)')).rows[0];
r.beginFrame({ x: last.PX, y: last.PY, z: last.VIEW_Z, yaw: last.YAW, pitch: last.PITCH, fov: 90 });
const vm = res.models.get(res.byName.get('progs/v_shot.mdl'));
console.log('vm', !!vm, vm?.mdl.numVerts, vm?.mdl.frames.length, 'scale', vm?.mdl.scale, 'origin', vm?.mdl.origin);
// instrument triangle()
let tri = 0; const orig = r.triangle.bind(r); r.triangle = (...a) => { tri++; return orig(...a); };
const anyNear = r.drawAlias(vm.mdl, 0, 0, [last.PX, last.PY, last.VIEW_Z], [-last.PITCH, last.YAW, 0], 128, { near: 1 });
console.log('viewmodel triangles drawn', tri, 'anyNear', anyNear, 'nonzero px', r.fb.filter((v) => v !== 0).length);
// teleport near grunt 68 at (0,576,24): stand 150 units south facing north (yaw 90)
await db.exec(`UPDATE ents SET x = 0, y = 426, z = 48, yaw = 90, vx = 0, vy = 0, vz = 0 WHERE id = (SELECT ent_id FROM player)`);
await db.exec(`EXECUTE PROCEDURE link_ent((SELECT ent_id FROM player))`);
const l2 = (await db.query('SELECT * FROM quake_tic(1,0,0,0,0,0,0,1,0)')).rows[0];
console.log('player now', l2.PX, l2.PY, l2.PZ, 'leaf', l2.LEAF);
const v = (await db.query('SELECT * FROM view_setup')).rows[0];
console.log('view leaf', v.LEAF, 'pvs', v.PVS.length);
console.log('grunt', JSON.stringify((await db.query(`SELECT id, leaf, leafs, CAST(x AS INTEGER) x, CAST(y AS INTEGER) y, CAST(z AS INTEGER) z, st, pvs_visible('${v.PVS}', leaf) vis FROM ents WHERE id = 68`)).rows));
console.log('frame_ents', JSON.stringify((await db.query('SELECT * FROM frame_ents')).rows));
await db.close(); process.exit(0);
