import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { FirebirdBrowser, DirectTransport } from 'firebird-wasm/browser';
import { Pak } from '../src/pak.js';
import { createSchema, loadResources, loadMap, SQL_FILES } from '../src/loader.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sql = Object.fromEntries(SQL_FILES.map((n) => [n, fs.readFileSync(path.join(root, `sql/${n}.sql`), 'utf8')]));
const db = new FirebirdBrowser('memory://quake', { transport: new DirectTransport() });
await createSchema(db, sql);
const pak = new Pak(fs.readFileSync(path.join(root, 'public/pak/pak0.pak')).buffer);
const res = await loadResources(db, pak); await loadMap(db, pak, res, 'e1m1');
const t = () => performance.now();
async function time(label, q, n = 3) { const t0 = t(); let r; for (let i = 0; i < n; i++) r = await db.query(q, [], { rowMode: 'array' }); console.log(`${label.padEnd(50)} ${((t() - t0) / n).toFixed(1)} ms (${r.rows.length} rows)`); return r; }
const v = (await db.query('SELECT * FROM view_setup')).rows[0];
await db.exec(`DELETE FROM vis_faces`);
await db.exec(`INSERT INTO vis_faces (face) SELECT DISTINCT m.face FROM leaves l JOIN marksurfaces m ON m.id >= l.first_ms AND m.id < l.first_ms + l.num_ms WHERE l.id > 0 AND pvs_visible('${v.PVS}', l.id) = 1`);
const n = (await db.query('SELECT COUNT(*) c FROM vis_faces')).rows[0].C; console.log('vis_faces', n);
await time('faces IN vis', 'SELECT COUNT(*) FROM faces f WHERE f.id IN (SELECT v.face FROM vis_faces v)');
await time('faces JOIN vis', 'SELECT COUNT(*) FROM vis_faces v JOIN faces f ON f.id = v.face');
await time('faces JOIN vis JOIN verts', 'SELECT COUNT(*) FROM vis_faces v JOIN faces f ON f.id = v.face JOIN face_verts fv ON fv.face = f.id');
await time('… + ORDER BY', 'SELECT f.id, fv.seq FROM vis_faces v JOIN faces f ON f.id = v.face JOIN face_verts fv ON fv.face = f.id ORDER BY f.id, fv.seq');
await time('… + backface WHERE', `SELECT f.id, fv.seq FROM vis_faces v JOIN faces f ON f.id = v.face JOIN face_verts fv ON fv.face = f.id WHERE f.nx * ${v.EX} + f.ny * ${v.EY} + f.nz * ${v.EZ} - f.dist > 0 ORDER BY f.id, fv.seq`);
await time('IN variant + ORDER BY', `SELECT f.id, fv.seq FROM faces f JOIN face_verts fv ON fv.face = f.id WHERE f.id IN (SELECT v.face FROM vis_faces v) ORDER BY f.id, fv.seq`);
await time('IN variant + OR eid clause', `SELECT f.id, fv.seq FROM faces f JOIN face_verts fv ON fv.face = f.id WHERE ((0 = 0 AND f.id IN (SELECT v.face FROM vis_faces v)) OR (0 <> 0 AND f.model_id = 1)) ORDER BY f.id, fv.seq`);
await time('mark: pvs func', `SELECT COUNT(*) FROM leaves l WHERE l.id > 0 AND pvs_visible('${v.PVS}', l.id) = 1`);
await time('mark: pvs inline', `SELECT COUNT(*) FROM leaves l WHERE l.id > 0 AND BIN_AND(POSITION(SUBSTRING('${v.PVS}' FROM BIN_SHR(l.id - 1, 2) + 1 FOR 1), '0123456789abcdef') - 1, BIN_SHL(1, BIN_AND(l.id - 1, 3))) <> 0`);
await time('mark: pvs inline + range join', `SELECT COUNT(*) FROM leaves l JOIN marksurfaces m ON m.id >= l.first_ms AND m.id < l.first_ms + l.num_ms WHERE l.id > 0 AND BIN_AND(POSITION(SUBSTRING('${v.PVS}' FROM BIN_SHR(l.id - 1, 2) + 1 FOR 1), '0123456789abcdef') - 1, BIN_SHL(1, BIN_AND(l.id - 1, 3))) <> 0`);
await time('mark: distinct insert', `EXECUTE BLOCK AS BEGIN DELETE FROM vis_faces; INSERT INTO vis_faces (face) SELECT DISTINCT m.face FROM leaves l JOIN marksurfaces m ON m.id >= l.first_ms AND m.id < l.first_ms + l.num_ms WHERE l.id > 0 AND BIN_AND(POSITION(SUBSTRING('${v.PVS}' FROM BIN_SHR(l.id - 1, 2) + 1 FOR 1), '0123456789abcdef') - 1, BIN_SHL(1, BIN_AND(l.id - 1, 3))) <> 0; END`);
await time('frame_faces', 'SELECT * FROM frame_faces');
await db.close(); process.exit(0);
