// bench.mjs – where does a tic and a frame spend their time?
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FirebirdBrowser, DirectTransport } from 'firebird-wasm/browser';
import { Pak } from '../src/pak.js';
import { createSchema, loadResources, loadMap, SQL_FILES } from '../src/loader.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sql = Object.fromEntries(SQL_FILES.map((n) => [n, fs.readFileSync(path.join(root, `sql/${n}.sql`), 'utf8')]));
const db = new FirebirdBrowser('memory://quake', { transport: new DirectTransport() });
await createSchema(db, sql);
const pak = new Pak(fs.readFileSync(path.join(root, 'public/pak/pak0.pak')).buffer);
const res = await loadResources(db, pak);
await loadMap(db, pak, res, process.argv[2] ?? 'e1m1');
const t = () => performance.now();
async function time(label, q, n = 5) {
  const t0 = t();
  let r;
  for (let i = 0; i < n; i++) r = await db.query(q, [], { rowMode: 'array' });
  console.log(`${label.padEnd(44)} ${((t() - t0) / n).toFixed(1)} ms  (${r.rows.length} rows)`);
  return r;
}
const q1 = (s) => db.query(s).then((r) => r.rows[0]);
const pe = (await q1('SELECT ent_id e FROM player')).E;
const p = await q1(`SELECT x, y, z FROM ents WHERE id = ${pe}`);
await time('tic (1 tic, idle)', 'SELECT * FROM quake_tic(1, 0, 0, 0, 0, 0, 0, 1, 0)');
await time('tic (1 tic, walking)', 'SELECT * FROM quake_tic(1, 1, 0, 0, 0, 0, 0, 1, 0)');
await time('player_think only', 'EXECUTE BLOCK AS BEGIN EXECUTE PROCEDURE player_think(0.05, 1, 0, 0, 0, 0, 0, 1, 0); END');
await time('run_pushers', 'EXECUTE BLOCK AS BEGIN EXECUTE PROCEDURE run_pushers(0.05); END');
await time('run_physics', 'EXECUTE BLOCK AS BEGIN EXECUTE PROCEDURE run_physics(0.05); END');
await time('trace_move (player box, 100 units fwd)', `SELECT * FROM trace_move(${pe}, -16, -16, -24, 16, 16, 32, ${p.X}, ${p.Y}, ${p.Z}, ${p.X}, ${p.Y + 100}, ${p.Z}, 0)`);
await time('trace_move (point, 2048 units)', `SELECT * FROM trace_move(${pe}, 0, 0, 0, 0, 0, 0, ${p.X}, ${p.Y}, ${p.Z + 22}, ${p.X}, ${p.Y + 2048}, ${p.Z + 22}, 0)`);
await time('trace_hull world only', `SELECT * FROM trace_hull(1, (SELECT hull1 FROM models WHERE id = (SELECT world_model FROM game)), 0, 0, 0, ${p.X}, ${p.Y}, ${p.Z}, ${p.X}, ${p.Y + 100}, ${p.Z})`);
await time('point_leaf', `SELECT point_leaf(${p.X}, ${p.Y}, ${p.Z}) FROM rdb$database`);
await time('link_ent(player)', `EXECUTE BLOCK AS BEGIN EXECUTE PROCEDURE link_ent(${pe}); END`);
await time('fly_move', `SELECT * FROM fly_move(${pe}, 0.05)`);
const m = (await q1("SELECT FIRST 1 id FROM ents WHERE mtype IS NOT NULL AND st = 'stand'")).ID;
await time('monster_think (standing)', `EXECUTE BLOCK AS BEGIN EXECUTE PROCEDURE monster_think(${m}); END`);
await time('find_target', `SELECT find_target(${m}) FROM rdb$database`);
await time('visible(monster, player)', `SELECT visible(${m}, ${pe}) FROM rdb$database`);
await db.exec(`UPDATE ents SET enemy_id = ${pe}, st = 'run', anim = NULL WHERE id = ${m}`);
await time('monster_think (running)', `EXECUTE BLOCK AS BEGIN EXECUTE PROCEDURE monster_think(${m}); END`);
await time('move_step', `SELECT move_step(${m}, 5, 5, 0) FROM rdb$database`);
await time('view_setup', 'SELECT * FROM view_setup');
await time('frame_faces', 'SELECT * FROM frame_faces');
await time('frame_faces_fast', 'SELECT * FROM frame_faces_fast');
await time('frame_ents', 'SELECT * FROM frame_ents');
await time('frame_lightstyles', 'SELECT * FROM frame_lightstyles');
const v = await q1('SELECT * FROM view_setup');
await time('mark leaves (pvs+sphere)', `SELECT COUNT(*) FROM leaves l WHERE l.id > 0 AND pvs_visible('${v.PVS}', l.id) = 1`);
await time('mark faces (insert distinct)', `EXECUTE BLOCK AS BEGIN DELETE FROM vis_faces; INSERT INTO vis_faces (face) SELECT DISTINCT m.face FROM leaves l JOIN marksurfaces m ON m.id >= l.first_ms AND m.id < l.first_ms + l.num_ms WHERE l.id > 0 AND pvs_visible('${v.PVS}', l.id) = 1; END`);
console.log('ents near player in pvs:', (await db.query(`SELECT e.id, e.classname, e.leaf, e.leafs, pvs_visible('${v.PVS}', e.leaf) vis FROM ents e WHERE e.model_id IS NOT NULL AND e.id <> ${pe} ORDER BY vlen(e.x - ${p.X}, e.y - ${p.Y}, e.z - ${p.Z}) ROWS 6`)).rows);
await db.close();
process.exit(0);
